import React from "react";
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/ThemeContext";
import "react-toastify/dist/ReactToastify.css";
import LoginContext from "@/loginContext/LoginContext";

export const metadata = {
  title: "KriShnamBlog",
  description: "Generated by krishnam Bloging",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <LoginContext>
            <div className="container">
              <Navbar />
              {children}
              <Footer />
            </div>
          </LoginContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
